### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by wbond** [Kindari/SublimeXdebug#1]
This plugin looks like it could be really useful to a lot of developers. I short readme with the basics of how to use it would be nice.

**Comment by yriveiro** [comment]
Hi, 

First at all, thanks for develops this plugin

+1 to Readme file

**Comment by mavimo** [comment]
I try to install this plugin but i can't find how to configure/start application with XDebug, can you give us more info about how tow start an application with XDebug?

**Comment by Kindari** [comment]
This has been started by arturolinares but I will leave this open as a reminder to myself to improve upon it.

**Comment by jperocho** [comment]
How to start the debug?

**Comment by jotson** [comment]
Instructions have been added to the README in the latest version.
