### ISSUE TITLE
Can't find URL in .sublime-project file

### ISSUE THREAD

**Issue by jbeales** [Kindari/SublimeXdebug#13]
I'm getting the status message "Xdebug: No URL defined in project settings file." but my URL _is_ defined in my project settings file. Here's what my whole file looks like:

```
{
"folders":
[
    {
        "path": "/Users/John/Work/companyname/working-copy"
    }
],

"settings":
{
    "xdebug": { "url": "http://companyname.local" }
}
}
```

I've also tried using the .sublime-project file that looks like this:

```
{
"folders":
[
    {
        "path": "/Users/John/Work/companyname/working-copy"
    }
],

"xdebug": { "url": "http://companyname.local" }

}
```

The .subime-project file resides in the directory /Users/John/Work/companyname/working-copy/nbproject  (I'm converting from NetBeans).

This is all on OS X 10.7.

**Comment by jotson** [comment]
The second syntax is correct. The plugin looks for your .sublime-project file in the root of your project. In this case:

```
/Users/John/Work/companyname/working-copy/whatever.sublime-project
```

**Comment by jbeales** [comment]
That's why it can't find the URL value then, since my .sublime-project is in a sub-folder.

I find it a little weird that the plugin has to go directly to the file, is there no API in ST2 to get settings info from the app itself? 

(I'm extremely new to Sublime Text, so if I'm completely ignorant let me know).

**Comment by jotson** [comment]
Not as far as I can tell. Not at the project level at any rate. All of the settings APIs are Package specific. I'm pretty new to ST2 as well.

**Comment by AaronJiang** [comment]
I must have followed the instruction by this plugin author, boom, the same error came out!

"Error trying to parse project: Trailing comma before closing bracket"
{
    "folders":
    [
        {
            "path": "/var/mycodes/"
        },
    ],

```
"settings": {
    "xdebug": { "url": "http://localhost" }
}
```

}

**Comment by AaronJiang** [comment]
{
    "folders":
    [
        {
            "path": "..."
        }
    ],

```
"settings": {
    "xdebug": { "url": "http://your.web.server" }
}
```

}

These codes may go pretty.
