### ISSUE TITLE
Threading issue when starting SublimeXdebug

### ISSUE THREAD

**Issue by jbeales** [Kindari/SublimeXdebug#14]
When I try to start debugging with SublimeXdebug I get the following error in the console:

```
Exception in thread Thread-102:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
   self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./Xdebug.py", line 281, in thread_callback
  File "./Xdebug.py", line 136, in accept
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)
```

And, it seems that SublimeXDebug doesn't end up listening for an Xdebug connection, even when I start one manually by adding XDEBUG_SESSION_START=sublime.xdebug to my project's URL, I get no reaction in SublimeXDebug, (although it seems to think it's debugging, as I have the option to stop debugging in the command palette).

**Comment by cretz** [comment]
This appears to happen because it's updating a status message in the wrong thread. The real question is why the port cannot be bound

**Comment by jbeales** [comment]
Interesting. I'd love to know as well ;) 

If there's anything I can do to help test, let me know.  I'm running build 2195 at the moment, (the dev build), but I also tried 2181 and the problem also exists there.

**Comment by jotson** [comment]
Are you sure nothing else is already listening on port 9000? When the problem is happening, what's the output of

```
netstat -anp | grep :9000
```

**Comment by jbeales** [comment]
```
netstat -an | grep :9000
```

Gives me no output.  I tried without the grep and didn't see any 9000 anything. The -p switch apparently requires a protocol, so I just dropped it after doing a bit of googling.

Netbeans, (which I'm trying to replace with Sublime in my daily work), does seem to be able to bind to port 9000, (note that I'm trying to do this with netbeans not running).

**Comment by jotson** [comment]
Try the version I just pushed (SHA: 584f553f06d7af7f57966970560b8b71b2b524f3). The threading errors may have been masking the real problem.

**Comment by jbeales** [comment]
That seems to have fixed the problem. I just was able to connect, stop at a breakpoint, see my call stack, and all that. Thanks!
