### ISSUE TITLE
Don't open files without breakpoints

### ISSUE THREAD

**Issue by Naatan** [Kindari/SublimeXdebug#16]
Hi, thanks for the addon, it's a great help!

One annoyance atm is that it opens the main file referenced automatically whenever debugging. For example when you have index.php, which is the file called from the browser, and it includes a file called include.php. Now when your breakpoint is include.php it will still load the file index.php in Sublime when executed.

Thanks

**Comment by Kindari** [comment]
So, your looking for a "auto run to first breakpoint" option? by default, it waits for instructions once connected to xdebug. but if we auto call "run" and there are no breakpoints set, it will finish execution immediately.

Maybe a solution, then, is on connect, if there are breakpoints already set, and a flag is set (say in your project settings), then auto run. If there are no breakpoints set, show the first file and wait for input.

**Comment by Naatan** [comment]
That sounds like a decent solution.

For the record, with a breakpoint set it goes straight to the first breakpoint for me, it does not stop at the first line and wait for input, it does open the first file referenced however.

**Comment by jotson** [comment]
Right, actually, the latest version calls "run" automatically (and continues listening automatically too). It's opening Naatan's index.php because it's responding to the <init> message in gui_callback on [line 322](https://github.com/Kindari/SublimeXdebug/blob/master/Xdebug.py#L322). Setting a breakpoint on the first line of that file and stopping there is a good idea if no breakpoints have been set.

**Comment by Naatan** [comment]
That's fine as long as it stays configurable. For my use-case I would not want the debugger to trigger any sort of behaviour what so ever unless it's running by a breakpoint I have set myself. Simply because I often work on large applications that have a lot of ajax requests going on in the background, so having it trigger on all those background requests would be a major annoyance.
