### ISSUE TITLE
error in example?

### ISSUE THREAD

**Issue by mikkeschiren** [Kindari/SublimeXdebug#17]
When trying to configure sublime with the settings in the readme, Sublime complains about trailing comma.

**Comment by mikkeschiren** [comment]
This worked for me:
{
    "folders":
    [
        {
            "path": "some/local/path"
        }
    ],

```
"settings":
[
    {
    "xdebug": { "url": "http://niftyserver" }
    }
]
```

}

**Comment by jotson** [comment]
That's what I get for modifying data without testing it. I fixed the sample. Thanks.
