### ISSUE TITLE
Session started but don't show anything

### ISSUE THREAD

**Issue by oakho** [Kindari/SublimeXdebug#22]
Hello,

I've an issue with the plugin, everytime I try to start debugging It seems to work, layouts open but don't show anything. 
When I reload my browser I can see in ST status "Page finished executing, reload to continue debugging" and nothing happens.

Here's my log of Xdebug :

```
I: Checking remote connect back address.
I: Remote address found, connecting to 127.0.0.1:9000.
I: Connected to client. :-)
-> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Stacks/MAMP5.4.3/apps/bloom/Public/index.php" language="PHP" protocol_version="1.0" appid="15139" idekey="sublime.xdebug"><engine version="2.3.0dev"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2012 by Derick Rethans]]></copyright></init>

<- run -i 1
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="run" transaction_id="1" status="stopping" reason="ok"></response>
```

I've tried to test Xdebug with MacGDBP and it seems to work, I've also tried to run a "netstat -an | egrep 'Proto|LISTEN'" in Terminal and I get : 

```
tcp4       0      0  *.9000                 *.*                    LISTEN
```

Do you have an idea of what's going on ? I don't really know what to do to make it work with ST2 :(

Thanks in advance,
Antoine

**Comment by jotson** [comment]
It sounds like you haven't set a breakpoint on a line of PHP code or the
code for your breakpoints isn't being executed.

On Sun, Jun 24, 2012 at 12:13 PM, oakho <
reply@reply.github.com

**Comment by oakho** [comment]
Almost, in fact with your words I figured out that my Xdebug skip all breakpoints that are not in my index.php. 'Trying to find a workaround.

Thanks anyway.

**Comment by lirantal** [comment]
Same issue as above.
1. Connection seems ok from netstat
2. Xdebug doesn't show anything on the bottom windows
3. Host which ST2 runs on is an Ubuntu 12.04 64bit with the python2.6 copied to <st2 folder>/lib

I'm debugging a plain test.php file and set the breakpoints on some php code.
Any ideas?

**Comment by joetech** [comment]
lirantal: Are you writing an xdebug log?  If so, what's the output?  I'm still having issues, too, but maybe we can share notes.

**Comment by lirantal** [comment]
I don't have the setup anymore but I didn't notice anything specific in the logs when I was testing it.
I am not sure if the reasons that were given here regarding the file locations being different on 2 hosts are the 'whole picture' because I tried to circumvent that by editing and setting a hard-coded path in the plugins but it didn't help.

**Comment by lirantal** [comment]
Checkout my comments on: https://github.com/Kindari/SublimeXdebug/issues/42

**Comment by g105b** [comment]
2 out of 3 dev machines in my office are experiencing this exact issue, but there is one machine that works fine. Same OS (Ubuntu 12.10), same Sublime version (2217), same PHP install (5.4.6), same browser (Chrome 24).

Why does one machine work when two don't? Very confused by this one... trying to work out the common denominator.

**Comment by lirantal** [comment]
As pointed out before, this seems to be an issue with translating the exact
file system path and to that I replied already that I believe I have
changed all areas in code to reflect the exact same file path locations on
both the local and remote servers, although to no avail as it's still not
working right.

Would appreciate if someone can shed a light on this issue (debugging
remotely)

On Tue, Jan 15, 2013 at 9:19 PM, Greg Bowler notifications@github.comwrote:

> 2 out of 3 dev machines in my office are experiencing this exact issue,
> but there is one machine that works fine. Same OS (Ubuntu 12.10), same
> Sublime version (2217), same PHP install (5.4.6), same browser (Chrome 24).
> 
> Why does one machine work when two don't? Very confused by this one...
> trying to work out the common denominator.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Kindari/SublimeXdebug/issues/22#issuecomment-12284168.

## 

## 

Sincerely, Liran Tal

**Comment by ULazdins** [comment]
Solved this problem with removing all spaces from path to my WAMP installation
