### ISSUE TITLE
Add remote debugging and path mapping to SublimeXdebug

### ISSUE THREAD

**Issue by pete-otaqui** [Kindari/SublimeXdebug#27]
I run my server on a virtual machine, and share the code directories from my host to the VM.  The result is that the path to the files from the server's point of view start like this:

/media/sf_code/application/....

And on my host machine are like this:

/home/pete/projects/application/....

IDEs such as Netbeans, Eclipse and PHPStorm allow the user to setup path mappings between a server and the debug client, which enabled debugging in this context.

Is there any possibility of adding this to SublimeXdebug?

**Comment by jotson** [comment]
It's something we're aware of and we have a plan. See #26.
