### ISSUE TITLE
Need a mapping configuration option

### ISSUE THREAD

**Issue by ryall** [Kindari/SublimeXdebug#35]
When the file path on the host machine differs to the local machine, the system will be unable to find the file. This is a common situation when using a VM.

An option is needed to map remote paths to local paths. 

For example:
`/var/www/someproject` -> `X:\someproject`

**Comment by Kindari** [comment]
This is planned, I hoped to implement it a few weeks ago but got caught up in work. Might have some freetime this weekend and will keep this in mind!

**Comment by ryall** [comment]
Great, thanks Kindari! :)

**Comment by ryall** [comment]
Ah just noticed it's already open in #26
