### ISSUE TITLE
ImportError: No module named pyexpat

### ISSUE THREAD

**Issue by arturolinares** [Kindari/SublimeXdebug#5]
I'm getting this error in the console when the xdebug connection is stablished:

```<socket._socketobject object at 0x51c7670> ('127.0.0.1', 55656)
Traceback (most recent call last):
  File "./Xdebug.py", line 273, in gui_callback
    init = protocol.read().firstChild
  File "./Xdebug.py", line 78, in read
    document = parseString(data)
  File ".\xml\dom\minidom.py", line 1927, in parseString
  File ".\xml\dom\expatbuilder.py", line 32, in <module>
  File ".\xml\parsers\expat.py", line 4, in <module>
ImportError: No module named pyexpat

```
```

**Comment by Kindari** [comment]
Operating System?

**Comment by arturolinares** [comment]
Linux. 
------Mensaje original------
De: William Cahill-Manley
Para: Arturo Linares Goenaga
Asunto: Re: [SublimeXdebug] ImportError: No module named pyexpat (#5)
Enviado: 22 mar, 2012 15:33

Operating System?

---

**Comment by Kindari** [comment]
https://github.com/clemos/haxe-sublime2-bundle/issues/17

Looks like a similar problem is in this thread. I will keep investigating. Could you provide the following?

Distribution / version

python --version

in sublime console:
import sys
print sys.version

**Comment by mavimo** [comment]
same error here:

``` python
import sys
print sys.version

2.6.6 (r266:84292, Jun 16 2011, 22:27:44) 
[GCC 4.4.5]
```

**Comment by mavimo** [comment]
Ok, I find a solution. On ubuntu 10.10  there are some python libraries on:

``` bash
/usr/lib/python2.6/lib-dynload/
```

so, open console and write:

``` python
import sys
sys.path.append("/usr/lib/python2.6/lib-dynload/")
```

now problem desappair :)

**Comment by arturolinares** [comment]
Ubuntu 11.10

```
$ python --version
Python 2.7.2+
```

Sublime console:

```
>>> import sys
>>> print sys.version
2.6.6 (r266:84292, Jun 16 2011, 22:27:44) 
[GCC 4.4.5]
```

**Comment by arturolinares** [comment]
Right, solved it with mavimo instructions and installing python:

```
$ sudo apt-get install python2.6
```

What should happen when selecting Status in the debugger menu?

**Comment by Kindari** [comment]
I just fixed an issue in that, so repull before trying again, but it tells you what status the debugger is in. It places the message in the status bar, it will only be there for about 5 seconds. usually in the form of "ok: starting" or "ok: stopping"

Glad your issue was resolved.

**Comment by arturolinares** [comment]
Sweet! thanks a lot.

**Comment by Kindari** [comment]
If you completely restart ST2, do you have to append that path to sys.path again? If so I can see that being a pain.

**Comment by arturolinares** [comment]
Yes. I just saw in the forums it enough to add a symlink to avoid that. I'll update the docs.

**Comment by bogdanbartis** [comment]
I'm having the same problem, unfortunatelly after the path append I get another error:

<pre>
ImportError: /usr/lib/python2.7/lib-dynload/pyexpat.so: undefined symbol: PyCapsule_New
</pre>


I've tried searching for a solution but to no avail.

<strong>Ubuntu 12.04</strong>

<pre>
$ python --version
Python 2.7.3
</pre>


<pre>
>>> import sys
>>> print sys.version
2.6.6 (r266:84292, Jun 16 2011, 22:35:51) 
[GCC 4.4.5]
</pre>


Any help would be appreciated. Thanks

**Comment by FedorKononov** [comment]
I'm having the same problem as helixdev

**Comment by jotson** [comment]
Have you guys tried the new instructions re: python 2.6 and pyexpat in the README? In the Troubleshooting section.

**Comment by FedorKononov** [comment]
It helps. Thanks a lot!

**Comment by ElijahLynn** [comment]
The readme text fixes this, one question though, there is a python26.zip file in the directory by default. What is that for? `/usr/lib/sublime-text-2/lib/python2/python26.zip`

**Comment by themroc5** [comment]
i guess its being used from sublime itself...

**Comment by temple** [comment]
I'm still having initiall issue.

_On bash_

```
$ pwd
> /usr/lib/python2.7/lib-dynload

$ ls *expat*
> pyexpat.so
```

_On Sublime_

``` python
>>> import sys
>>> sys.path.append("/usr/lib/python2.7/lib-dynload/")
```

Can it only run with python 2.6?

**Comment by temple** [comment]
@jotson which README are you **exactly** referring to?

**Comment by jotson** [comment]
This one here: https://github.com/Kindari/SublimeXdebug

**Comment by temple** [comment]
Ok thanks. 

I've found this post so useful: https://blog.bitbadger.net/index.php/2012/11/22/error-importing-pyexpat-in-sublime-on-linux/
