### ISSUE TITLE
Windows path with space character

### ISSUE THREAD

**Issue by leighelse** [Kindari/SublimeXdebug#72]
I've written this up more fully in StackExchange when I was initially looking for an answer: http://stackoverflow.com/questions/17265783/xdebug-never-stops-at-my-sublime-text-breakpoints/17266299#17266299

Since then I've found the cause of the problem: A space in the Windows path defeats the setting of breakpoints. 

If I try to set a breakpoint in the following file ...

```
C:\Users\work\My Projects\ElseApps\EAFF\code\approot\core\etc\eaff-index.php
```

... I get the following error response ...

```
<error code="1"><message><![CDATA[parse error in command]]></message></error>
```

However, a short-term hack of the Xdebug.py file at line 221 resolves this:

```
def uri(self):
    rawpath = os.path.realpath(self.view.file_name())
    outpath = rawpath.replace("My Projects", "MyProj~1")
    # return 'file://' + os.path.realpath(self.view.file_name())
    return 'file://' + outpath
```

This is obviously not a solution, just a test.

I wonder whether a good solution would be to use the path exactly as set in the Sublime Text project file. I have an 8.3 path set, but it's obviously not being directly used.

```
"path": "/C/Users/work/MyProj~1/ElseApps/EAFF/code"
```

**Comment by martomo** [comment]
This is indeed because the spacing in your file path you are trying to set the breakpoint.
It would be better to encode the uri when sending the filename to the server instead of using replacing.

``` python
import urllib2

def uri(self):
     return urllib2.quote('file://' + os.path.realpath(self.view.file_name()))
```

To make sure the plugin also opens the proper window of receiving response from debugger, decode the filename from response.

``` python
class XdebugContinueCommand(sublime_plugin.TextCommand):
     #...
     def callback(self, state):
          #...
          for child in res.childNodes:
               if child.nodeName == 'xdebug:message':
                    # Decode filename from response
                    xdebug_current = show_file(self.view.window(), urllib2.unquote(child.getAttribute('filename')))

          #...
          if (res.getAttribute('status') == 'break'):
               #...
               for child in res.childNodes:
                    if child.nodeName == 'stack':
                         # Show filename properly in Xdebug Stack window
                         propFile = urllib2.unquote(child.getAttribute('filename'))

def show_file(window, uri):
     # Decode uri
     uri = urllib2.unquote(uri)
     if window:
          #...
```

**Comment by leighelse** [comment]
Thank you! That improves things considerably. 

Given that development seems to have stalled, I guess I'll close this issue.

Incidentally, now that I have the debugger running, I find that it doesn't have full depth variable inspection, which is a show stopper. I'll keep looking for alternative solutions, but for now I'll have to stick with my existing IDE.

Thank you again Martomo.
