### ISSUE TITLE
Not working... abandonware?

### ISSUE THREAD

**Issue by dtrenz** [Kindari/SublimeXdebug#75]
I installed this via package manager and I get the package, but there are no prefs, layouts, toolbars, menus, etc.

**Comment by martomo** [comment]
@dtrenz What version of Sublime Text are you using?

In case you are using Sublime Text 3, this repository might not work properly and I would recommend to look into other forks of this repository, a lot of people picked up this project and made their own adjustments/features.

I have created a new [**repository**](https://github.com/martomo/SublimeTextXdebug) that is compatible with Sublime Text 3 (and 2), which also supports inspection of nested objects, remote debugging and more.

**Comment by dtrenz** [comment]
I am using version 2.0.2 Build 2221, not 3.

At one point I had both this package and the Xdebug Client package installed, but have since removed both, then tried again only with this one.  Still no luck.  The weird part is that this worked for a bit, but now it doesn't work when I reinstall it.

**Comment by martomo** [comment]
Are you trying to debug a script locally or remotely?

What operating system(s) are you using?

**Comment by dtrenz** [comment]
I see now... "Xdebug Client" is the new package, right?  I just installed that and I get prefs, tools, etc but when I start debugging, I don't get anything in the xdebug windows.  And I'm not able to inspect the value of vars.

Debugging PHP locally on OS X Mountain Lion

**Comment by martomo** [comment]
Do you have by any chance a symbolic link configured on your project directory?

Are you sure you are passing the `XDEBUG_SESSION_START` parameter in the REQUEST on the page you are trying to debug? (http://xdebug.org/docs/remote#activate_debugger)

**Comment by dtrenz** [comment]
I got it working now.  Using the new client you linked to + made sure to set up my trigger GET params (using chrome plugin) to set "sublime.xdebug" as IDE, and adjusted php.ini xdebug config to match instructions from the new client repo.

Thanks for your help.
